import React from "react"
import Typography from "typography"

export default () =>
  <div style={{ margin: '3rem auto', maxWidth: 600 }}>
    <h1>About *</h1>
    <p>
      Imaginary Radio Stations is a project by three Slovenian music enthusiasts, DJs and artists, founded in Berlin. Its existence is as an expression of pure intent without fitting into flavor-of-the-week hype columns, purist approaches and associated microscenes. The aim is timelessness, always inspired by concrete ambients, settings and states of mind, beckoning the wandering ear to tune in. Its concept reflects the commodification and atomization of music culture. By blurring the lines between genres and styles, producers and consumers it mirrors a fragmented culture of innumerable acteurs where everyone curates their own imaginary radio. 
    </p>
    <h2>pak</h2>
    <p> 
      Pak is a DJ and absolute music enthusiast from Buenos Aires, Argentina. Born to a 2nd generation Slovenian family, he has held a love for music since his early teens. After moving to Europe in his twenties, he eventually settled in Ljubljana, Slovenia. He got involved in the local electronic music scene and soon started working as a music journalist and curator on the cult Radio Student, Europe’s oldest independent radio station. At the same time, he started performing as a DJ, recording podcasts and playing at selected venues in Ljubljana. Co-created the Pelje music community blog with industrial designer and music technology aficionado Tilen Sepic. 
    </p>
    <h2>evano</h2>
    <p>
      Evano is a DJ / producer from Ljubljana, Slovenia. His music journey began back in 2004 when he got his first DJing experiences. One year later, alongside his friend Peter Jenko, he established a renowned Slovenian electronic music society called Phonotouch where they organized DJ workshops for youth, sharing their knowledge of DJing and also raising awareness of quality underground electronic music. In 2010 he teamed up with a young producer Vid Vai and Alex Long, an already established techno matador. Together they spent hours in the studio, experimenting with new sounds and unconventional approaches, sharing their knowledge and experiences. Soon after that he released his first EP called »Caviar« on the Canadian label Stereo Tension Records. At that time, he was discovered by one of the most active DJ collectives in Slovenia – Colours In Music. Recently released two EPs (2016 / 2017) on the newly established Slovenian label Phi. His music has since become noticed and praised by many well-known artists such as Dr. Nojoke, Pheek and Cleymoore who also invited him to collaborate in another artist collective called Pluie/Noir (based at Berlin’s Club der Visionaere). His interest in sound collage, and music for theatre and dance performance, has recently found a home under the project AMOLAB. With wide-reaching tastes and an ear for the unusual, Evano plays music for connoisseurs and those with a sense of adventure.
    </p>
    <h2>1983</h2> 
    <p>
      DJ 1983 was born in Ljubljana, Slovenia. Initially turned on to music via playing guitar and drums in punk bands he too gazed into the mirrorball during his late teens and developed a passion for electronic music. DJ / producer with 15 years of DJ sets and live performances under his belt. Co-founder of Scienceofuse, an independent electronic music collective / record label (2006-2016). Vice-manager and resident of the now infamous Gumitwist club nights (hosting international heavyweights like A Guy Called Gerald, Alexander Robotnick, Container, Legowelt, Morphosis, Octave One and many, many more) at the legendary Klub K4, co-shaping the Ljubljana electronic music scene from 2008-2016. Shared a studio and often collaborated with Scienceofuse co-members Wichiwaka and Electronic Badminton King on tracks and live peformances. He is a regular contributor to the long-standing Chilli Space dub-techno / electronica compilation series (est.2002) and associated events as well as frequently gracing the decks at Elektroliza, a series of electro nights at club Channel Zero, Ljubljana. Has collaborated with up-and-coming local imprints like Stiropor, Elektroliza, Inn Kick and Sezam. 
    </p>
  </div>